### ISSUE TITLE
install with pip ?

### ISSUE THREAD

**Issue by juanpabloaj** [juancarlospaco/octopussh#1]
why don't create a pip package?, and change this lines

``` bash
sudo wget -O /usr/bin/octopussh https://raw.githubusercontent.com/juancarlospaco/octopussh/master/octopussh
sudo chmod +x /usr/bin/octopussh
```

to

```
pip install octopussh
```

**Comment by ghost** [comment]
I have to upload all my Apps to PyPI.
Thanks for using it, I never knew it was useful to someone :smiley_cat:

**Comment by juanpabloaj** [comment]
;)

... a simple way to create a pypi setup.py file

https://github.com/juanpabloaj/pip-init

:bowtie:

**Comment by ghost** [comment]
Been trying to Upload the Wheel to PyPI but it keeps failing.

``` shell
Server response (500): Internal Server Error
```

 or

``` shell
Upload failed (400): Binary wheel for an unsupported platform
```

Already got the setup.py and the wheel on my local to install, but PyPI fails.

@juanpabloaj if you know how to do it properly, please feel free to send a pull request with all the stuff needed.

Im also interested on Uploading some new Apps I have on my other repos...

:sob:

**Comment by juanpabloaj** [comment]
I made a PR (https://github.com/juancarlospaco/octopussh/pull/2) with a setup.py, and I changed the readme from markdown to rst because pypi use the rst format.

**Comment by juanpabloaj** [comment]
more detail about pip package and pypi in 

https://hynek.me/articles/sharing-your-labor-of-love-pypi-quick-and-dirty/

you can test your installation with virtualenv, more info in this spanish presentation 

https://speakerdeck.com/juanpabloaj/empaquetando-y-distribuyendo-codigo-python-con-pip

**Comment by ghost** [comment]
**Done !**  :smiley_cat: 

```
sudo pip3 install octopussh
```
- https://pypi.python.org/pypi/octopussh

Thanks @juanpabloaj !, Im going to recomment **PIP-Init**

:bomb:
